# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20170927_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='b_day',
            field=models.DateField(default='1776-07-04'),
        ),
    ]
