# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_user',
            field=models.ManyToManyField(related_name='_user_friends_user_+', to='login_app.User'),
        ),
    ]
